# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objection',
            options={'verbose_name': 'مشکل درسی', 'verbose_name_plural': 'مشکلات درسی'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
    ]
