# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0002_auto_20170116_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='objection',
            unique_together=set([('category', 'offered_course', 'second_course', 'course_name', 'message')]),
        ),
    ]
