# Generated by Django 2.1.2 on 2018-10-02 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objection', '0003_auto_20180127_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objection',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
