# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2)),
                ('reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='locker',
            name='conditons',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='numberID',
        ),
        migrations.AddField(
            model_name='locker',
            name='rack1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='1+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='2+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='3+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='4+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='5+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='6+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='7+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='8+', to='locker.rack'),
        ),
        migrations.AddField(
            model_name='locker',
            name='rack9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='9+', to='locker.rack'),
        ),
    ]
