# Generated by Django 2.1.2 on 2019-09-29 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190928_1857'),
        ('locker', '0002_rack_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Transaction'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.Rack'),
        ),
    ]
