# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-23 21:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20180923_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
