# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-24 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0003_auto_20180923_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='reciever',
        ),
    ]
