# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-29 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_remove_rack_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='number',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack1',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack2',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack3',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack4',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack5',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack6',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack7',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack8',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='rack9',
        ),
    ]
