# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-29 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0005_auto_20180929_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(0, 'available'), (1, 'unavailable')], default=0),
        ),
        migrations.AddField(
            model_name='rack',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
