# Generated by Django 2.1.1 on 2018-09-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_auto_20180929_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locker',
        ),
    ]
