# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-01 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_auto_20180929_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locker',
        ),
        migrations.AddField(
            model_name='rack',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rack',
            name='receivie_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 1, 17, 46, 12, 351157, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
