# Generated by Django 2.1.2 on 2018-10-04 17:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0007_delete_locker'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=20000)),
                ('is_success', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rack',
            name='receivie_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 4, 17, 36, 22, 81699, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.rack'),
        ),
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
