# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-01 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locker', '0007_auto_20181001_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=20000)),
                ('is_success', models.NullBooleanField(default=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locker.rack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
