# Generated by Django 2.1.2 on 2018-10-05 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_auto_20181004_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='authority',
            field=models.CharField(default=django.utils.timezone.now, max_length=63),
            preserve_default=False,
        ),
    ]
