# Generated by Django 2.1.2 on 2019-09-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0008_auto_20190930_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='locker',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
        migrations.DeleteModel(
            name='sell',
        ),
    ]
