# Generated by Django 2.1.2 on 2019-09-19 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, '------------'), (1, 'شورای صنفی'), (3, 'لابی'), (5, 'کتابخانه'), (7, 'نمازخانه'), (9, 'کلاس ها'), (11, 'سالن مطالعه'), (13, 'سایت'), (15, 'اغذیه فروشی'), (17, 'ساختمان دانشکده'), (19, 'تاسیسات'), (30, 'سایر موارد')])),
                ('category_optional', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'منتظر تایید'), (2, 'تایید نشده'), (3, 'منتظر پاسخ'), (4, 'مشاهده شده'), (5, 'پاسخ داده شده')])),
                ('like', models.ManyToManyField(blank=True, related_name='issue_liked_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مشکل رفاهی',
                'verbose_name_plural': 'مشکلات رفاهی',
            },
        ),
        migrations.CreateModel(
            name='IssueReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue.IssueReply'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
