# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20161030_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category_optional',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
