# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_issue_category_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'مشکل رفاهی', 'verbose_name_plural': 'مشکلات رفاهی'},
        ),
        migrations.AlterModelOptions(
            name='issuereply',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ\u200cها'},
        ),
    ]
