# Generated by Django 2.1.2 on 2018-10-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_auto_20181002_1216'),
        ('issue', '0005_auto_20181004_1736'),
    ]

    operations = [
    ]
