# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('course_number', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.SmallIntegerField(default=1)),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'پاییز'), (2, 'بهار'), (3, 'تابستان')])),
                ('exam_time', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('details', models.CharField(max_length=1023)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offeredcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Professor'),
        ),
        migrations.AddField(
            model_name='offeredcourse',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EducationalYear'),
        ),
        migrations.AlterUniqueTogether(
            name='offeredcourse',
            unique_together=set([('course', 'group_number', 'term', 'year')]),
        ),
    ]
