# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180127_0657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offeredcourse',
            unique_together=set([('course', 'group_number', 'term', 'year')]),
        ),
    ]
