# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='authority',
            field=models.CharField(default=-1, max_length=63),
            preserve_default=False,
        ),
    ]
