# Generated by Django 2.1.2 on 2018-10-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_donate_authority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='authority',
        ),
    ]
