# Generated by Django 2.1.2 on 2019-09-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('type', models.IntegerField(choices=[(1, 'شارژ نقدی'), (2, 'شارژ آنلاین'), (3, 'انتقال وجه'), (4, 'استفاده از خدمات شورا')], verbose_name='نوع تراکنش')),
                ('is_successfully', models.BooleanField(default=False, verbose_name='موفقیت')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination', to=settings.AUTH_USER_MODEL, verbose_name='مقصد')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin', to=settings.AUTH_USER_MODEL, verbose_name='مبدا')),
            ],
        ),
    ]
