# Generated by Django 2.1.2 on 2019-09-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='Authority',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
