# Generated by Django 2.1.2 on 2018-10-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20181002_1216'),
        ('base', '0002_auto_20180930_1235'),
    ]

    operations = [
    ]
