# Generated by Django 2.1.2 on 2018-10-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_merge_20181006_2248'),
        ('base', '0003_merge_20181007_1520'),
    ]

    operations = [
    ]
